// <auto-generated />
using System;
using KejaHUnt_PropertiesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KejaHUnt_PropertiesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250507124240_PropertyPolicyDescription")]
    partial class PropertyPolicyDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneralFeaturesProperty", b =>
                {
                    b.Property<long>("GeneralFeaturesId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertiesId")
                        .HasColumnType("bigint");

                    b.HasKey("GeneralFeaturesId", "PropertiesId");

                    b.HasIndex("PropertiesId");

                    b.ToTable("GeneralFeaturesProperty");
                });

            modelBuilder.Entity("IndoorFeaturesProperty", b =>
                {
                    b.Property<long>("IdoorFeaturesId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertiesId")
                        .HasColumnType("bigint");

                    b.HasKey("IdoorFeaturesId", "PropertiesId");

                    b.HasIndex("PropertiesId");

                    b.ToTable("IndoorFeaturesProperty");
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.GeneralFeatures", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeneralFeatures");
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.IndoorFeatures", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IndoorFeatures");
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.OutDoorFeatures", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutDoorFeatures");
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.Policy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.PolicyDescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyDescriptions");
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DoorNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("OutDoorFeaturesProperty", b =>
                {
                    b.Property<long>("OutdoorFeaturesId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertiesId")
                        .HasColumnType("bigint");

                    b.HasKey("OutdoorFeaturesId", "PropertiesId");

                    b.HasIndex("PropertiesId");

                    b.ToTable("OutDoorFeaturesProperty");
                });

            modelBuilder.Entity("PolicyDescriptionProperty", b =>
                {
                    b.Property<long>("PolicyDescriptionsId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertiesId")
                        .HasColumnType("bigint");

                    b.HasKey("PolicyDescriptionsId", "PropertiesId");

                    b.HasIndex("PropertiesId");

                    b.ToTable("PolicyDescriptionProperty");
                });

            modelBuilder.Entity("PolicyProperty", b =>
                {
                    b.Property<long>("PoliciesId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertiesId")
                        .HasColumnType("bigint");

                    b.HasKey("PoliciesId", "PropertiesId");

                    b.HasIndex("PropertiesId");

                    b.ToTable("PolicyProperty");
                });

            modelBuilder.Entity("GeneralFeaturesProperty", b =>
                {
                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.GeneralFeatures", null)
                        .WithMany()
                        .HasForeignKey("GeneralFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IndoorFeaturesProperty", b =>
                {
                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.IndoorFeatures", null)
                        .WithMany()
                        .HasForeignKey("IdoorFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.PolicyDescription", b =>
                {
                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.Policy", "Policy")
                        .WithMany("PolicyDescriptions")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.Unit", b =>
                {
                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("OutDoorFeaturesProperty", b =>
                {
                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.OutDoorFeatures", null)
                        .WithMany()
                        .HasForeignKey("OutdoorFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolicyDescriptionProperty", b =>
                {
                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.PolicyDescription", null)
                        .WithMany()
                        .HasForeignKey("PolicyDescriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolicyProperty", b =>
                {
                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.Policy", null)
                        .WithMany()
                        .HasForeignKey("PoliciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KejaHUnt_PropertiesAPI.Models.Domain.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.Policy", b =>
                {
                    b.Navigation("PolicyDescriptions");
                });

            modelBuilder.Entity("KejaHUnt_PropertiesAPI.Models.Domain.Property", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
