# inventory.yml
all:
  children:
    ec2_servers:
      hosts:
        your-ec2-server:
          ansible_host: "{{ ec2_public_ip }}"
          ansible_user: "{{ ec2_user }}" 
          ansible_ssh_private_key_file: /tmp/ec2-key.pem