# inventory.yml
all:
  children:
    ec2_servers:
      hosts:
        your-ec2-server:
          ansible_host: "{{ ec2_public_ip }}"
          ansible_user: ubuntu  # or ec2-user for Amazon Linux
          ansible_ssh_private_key_file: ~/.ssh/your-key.pem